CREATE TABLE SYSCONFIG
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME varchar(255) NOT NULL,
	VALUE text
);

INSERT INTO SYSCONFIG (NAME, VALUE) VALUES("WEATHER_APIKEY", "84af7992ace2dd1b19d32a209737949e");
INSERT INTO SYSCONFIG (NAME, VALUE) VALUES("WEATHER_URL", "http://api.openweathermap.org/data/2.5/weather");
