CREATE TABLE SYSPLUGIN (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME VARCHAR(254) NOT NULL,
	MAINTABLENAME VARCHAR(254),
	ACTIVE INTEGER NOT NULL DEFAULT 0,
	MAINDLL VARCHAR(254) NOT NULL,
	SECONDARYDDLS TEXT
	);