CREATE TABLE USERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FIRSTNAME VARCHAR (254) NOT NULL,
    LASTNAME  VARCHAR (254) NOT NULL,
    USERNAME  VARCHAR (254) NOT NULL,
	PASSWD VARCHAR (254) NOT NULL,
	GEOLOCATION INTEGER);

INSERT INTO USERS (FIRSTNAME, LASTNAME, USERNAME, PASSWD) VALUES ("Admin", "Admin", "Admin", "Admin");



