CREATE TABLE [dbo].[USERS] (
    [ID]        INT           IDENTITY (1, 1) NOT NULL,
    [FIRSTNAME] VARCHAR (254) NOT NULL,
    [LASTNAME]  VARCHAR (254) NOT NULL,
    [USERNAME]  VARCHAR (254) NOT NULL,
    [PASSWD]    VARCHAR (254) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

